language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - 'node'

env:
  - NODE_ENV=test

cache:
  directories:
    - "node_modules"

before_script:
  - npm prune

before_install:
  - npm install -g coveralls@2 nyc@10.3

script:
  - npm run test

after_success:
  - npm run test:travis